/** Ações de auditoria padronizadas. */
export const AUDIT_ACTIONS = {
  AUTH_REGISTER: 'auth.register',
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_SWITCH_ORG: 'auth.switch_org',
  ORG_CREATED: 'org.created',
  MEMBER_CREATED: 'member.created',
  MEMBER_ROLE_CHANGED: 'member.role_changed',
  MEMBER_REMOVED: 'member.removed',
  LEAD_CREATED: 'lead.created',
  LEAD_STATUS_CHANGED: 'lead.status_changed',
  PARTY_CREATED: 'party.created',
  PARTY_DEDUPE: 'party.dedupe',
  TASK_CREATED: 'task.created',
  TASK_STATUS_CHANGED: 'task.status_changed',
  VISIT_CREATED: 'visit.created',
  PROPOSAL_CREATED: 'proposal.created',
  TIMELINE_CREATED: 'timeline.created',
  PROPERTY_CREATED: 'property.created',
  PROPERTY_UPDATED: 'property.updated',
  PROPERTY_ARCHIVED: 'property.archived',
  PROPERTY_ADDRESS_UPDATED: 'property.address_updated',
  PROPERTY_FINANCIAL_TERMS_UPDATED: 'property.financial_terms_updated',
  PROPERTY_OWNER_ADDED: 'property.owner_added',
  PROPERTY_OWNER_REMOVED: 'property.owner_removed',
  PROPERTY_FEATURE_ADDED: 'property.feature_added',
  PROPERTY_FEATURE_REMOVED: 'property.feature_removed',
  PROPERTY_MEDIA_CONFIRMED: 'property.media_confirmed',
  PROPERTY_MEDIA_DELETED: 'property.media_deleted',
  LISTING_CREATED: 'listing.created',
  LISTING_UPDATED: 'listing.updated',
  LISTING_STATUS_CHANGED: 'listing.status_changed',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
